name: Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Download Go modules
      run: cd native && go mod download

    - name: Build Linux
      run: |
      GOOS=linux GOARCH=amd64 cd native && go build -ldflags "-s" -o parquet-amd64.so -buildmode=c-shared .
      GOOS=linux GOARCH=arm64 cd native && go build -ldflags "-s" -o parquet-arm64.so -buildmode=c-shared .

    - name: Build Darwin
      run: | 
      GOOS=darwin GOARCH=amd64 cd native && go build -ldflags "-s" -o parquet-amd64.dylib -buildmode=c-shared .
      GOOS=darwin GOARCH=arm64 cd native && go build -ldflags "-s" -o parquet-arm64.dylib -buildmode=c-shared .

    - name: Get package version
      id: get_version
      run: |
        ls
        pwd
        VERSION=$(jq -r .version package.json)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "native/*.so,native/*.dylib,native/*.dll"
        tag: v${{ env.VERSION }}