name: Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [amd64, arm64]
        include:
          - os: macos-latest
            arch: arm64
          - os: ubuntu-latest
            arch: amd64

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Download Go modules
      run: cd native && go mod download

    - name: Build Linux
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        cd native
        CGO_ENABLED=1 GOOS=linux GOARCH=arm64 go build -ldflags "-s" -o parquet-arm64.so -buildmode=c-shared .
        CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -ldflags "-s" -o parquet-amd64.so -buildmode=c-shared .
        echo "${{ matrix.arch }} built"

    - name: Build Darwin
      if: startsWith(matrix.os, 'macos')
      run: |
        cd native
        CGO_ENABLED=1 GOOS=darwin GOARCH=arm64 go build -ldflags "-s" -o parquet-arm64.dylib -buildmode=c-shared .
        CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -ldflags "-s" -o parquet-amd64.dylib -buildmode=c-shared .
        echo "${{ matrix.arch }} built"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts-${{ matrix.os }}
        path: native/parquet-*.so,native/parquet-*.dylib

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        path: release

    - name: Get package version
      id: get_version
      run: |
        pwd
        ls
        VERSION=$(jq -r .version package.json)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release/**"
        tag: v${{ env.VERSION }}