name: Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: GOOS=linux GOARCH=amd64 cd native && go build -ldflags "-s" -o parquet-amd64.so -buildmode=c-shared .

    - name: Get Package version
      id: get_version
      run: echo "VERSION=$(jq -r .version < package.json)" >> $GITHUB_ENV

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "native/*.so,native/*.dylib,native/*.dll"
        tag: v${{ env.VERSION }}